import { Be_Vietnam_Pro } from 'next/font/google'
import Header from '@/components/shared/header'
import type { Metadata } from 'next'
import './globals.css'

const beVietnamPro = Be_Vietnam_Pro({ subsets: ['latin'], weight : ['400', '500', '700'] })

export const metadata: Metadata = {
  title: 'Manage | Frontend Mentor',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={beVietnamPro.className}>
        <Header />
        <main className='bg-pattern-desktop bg-no-repeat bg-right-top '>
          {children}
        </main>
      </body>
    </html>
  )
}
